### PR TITLE
[readme] add link to third party library

### PR DESCRIPTION
**Pull request by sw-yx**
## What was changed
add link to third party library

## Why?

- people often ask for Saga patterns, this has it
- encourage more people to write third party libraries, build an ecosystem around us

### CODE REVIEW

**Comment by cretz** [comment]
I think a well curated `awesome-temporal` repo w/ a README w/ all third party is better than littering third party links around each repo

**Review by flossypurse — APPROVED** [review]

**Comment by sw-yx** [comment]
leaving this to you an open qtn as to whether we have enough for a separate `awesome` repo or you just wanna keep it on readme for now

**Comment by cretz** [comment]
:+1: I personally am not sure a list would be reasonably maintained or even discoverable inside a samples repo. A samples repo doesn't seem like the place to curate third party utilities that aren't even samples. But I don't have a super-strong opinion, so if y'all really want this I can merge.

Otherwise, whether they do end up in documentation or an awesome repo or wherever, I'll defer to others.

**Comment by cretz** [comment]
Closing. We can include third party libraries in other documentation.

**Pull request closed without merging**
