### PR TITLE
Add a saga pattern sample

### PR DESCRIPTION
**Pull request by pavlo-v-chernykh**
## What was changed
Add a saga pattern sample.

## Why?
There is no saga pattern sample.

### CODE REVIEW

**Comment by cretz** [comment]
For most use cases, saga seems to "just properly use defer" in Go. We even had a saga impl suggested as part of the SDK at https://github.com/temporalio/sdk-go/pull/744 and we are still trying to decide how best to support saga pattern across SDKs at https://github.com/temporalio/sdk-features/issues/50. I will confirm with others the value of this sample (I saw it was a TODO in the README) and get back.

**Comment by pavlo-v-chernykh** [comment]
@cretz hi. Did you have a chance to talk with the team?

**Comment by cretz** [comment]
We can accept this, Can you sign the CLA?

**Comment by pavlo-v-chernykh** [comment]
@cretz, I'm glad to know.
I've signed the CLA.
Please, proceed.

**Review by cretz — APPROVED** [review]

**Comment by pavlo-v-chernykh** [comment]
@cretz, it looks like I do not have write access to this repository to merge the pull request. Please, merge it.

**Pull request merged**
