### PR TITLE
Add open telemetry sample

### PR DESCRIPTION
**Pull request by Quinn-With-Two-Ns**
Add open telemetry sample

Leaving as draft for two reasons:
* Due to some samples depending on an old server version I couldn't add newer otel SDKs so I temporarily removed them
* The unit test is not getting the correct spans and I suspect their is a bug with interceptors in the test enviorment

### CODE REVIEW

**Comment by emanuelef** [comment]
Hi, I have a similar problem with my PR: https://github.com/temporalio/samples-go/pull/296
That PR has been there for months but cannot be merged because of https://github.com/temporalio/samples-go/pull/293

**Comment by Quinn-With-Two-Ns** [comment]
@emanuelef Sorry I completely missed your PR or that it was blocked. I will create a PR to upgrade the server dependency.

**Comment by emanuelef** [comment]
@Quinn-With-Two-Ns I see as part of this PR some samples have been removed, did you need that to be able to use OpenTelemetry modules ? I might need to do the same in my PR, provided it makes sense to have both PRs been merged.

**Comment by emanuelef** [comment]
The imports where I'm having problems as well are:

In grpc-proxy and codec-server:
go.temporal.io/server/common/authorization
go.temporal.io/server/common/config

What would be the new way to import those modules ?

**Comment by emanuelef** [comment]
@Quinn-With-Two-Ns The PR https://github.com/temporalio/samples-go/pull/296 is ready to be merged

**Comment by Quinn-With-Two-Ns** [comment]
@emanuelef Thanks, sorry was out of the office.

**Pull request closed without merging**
